import { Locale } from 'date-fns';
import { ISupportedLanguage } from '../_utils/globals/locales';

export interface IThemeFontColors {
	primary1: string;
	primary2: string;
	primary3: string;
	primary4: string;
	primary5: string;
	secondary1: string;
	secondary2: string;
	secondary3: string;
	secondary4: string;
	secondary5: string;
	secondary6: string;
	white: string;
	altWhite: string;
	background: string;
	blue400: string;
	teal400: string;
	teal500: string;
	pink400: string;
	orange400: string;
	red400: string;
	red600: string;
	green600: string;
	purple400: string;
	grayAlpha: string;
	grayAlpha100: string;
	grayAlpha400: string;
	gray100: string;
	gray1: string;
	gray2: string;
	medgray1: string;
	medgray2: string;
	darkgray1: string;
	darkgray2: string;
	darkgray3: string;
	text: string;
	inverseText: string;
	black: string;
	checkboxUnselected: string;
	dropdown: string;
	accountNavigation: string;
	submenu: string;
	autosExpression: string;
	client: string;
	createNew: string;
	menuDark: string;
	menuLight: string;
	editorRow: string;
	editorElement: string;
	editorRepeatable: string;
	error: string;
	warning: string;
	success: string;
	info: string;
	successIcon: string;
	errorIcon: string;
	infoIcon: string;
	warningIcon: string;
}

export interface IThemeBackgroundColors {
	primary1: string;
	primary2: string;
	primary3: string;
	primary4: string;
	primary5: string;
	secondary1: string;
	secondary2: string;
	secondary3: string;
	secondary4: string;
	secondary5: string;
	secondary6: string;
	white: string;
	altWhite: string;
	background: string;
	blue400: string;
	teal400: string;
	teal500: string;
	pink400: string;
	red400: string;
	red600: string;
	green600: string;
	purple400: string;
	orange400: string;
	grayAlpha: string;
	grayAlpha100: string;
	grayAlpha400: string;
	gray100: string;
	gray1: string;
	gray2: string;
	medgray1: string;
	medgray2: string;
	darkgray1: string;
	darkgray2: string;
	darkgray3: string;
	text: string;
	inverseText: string;
	black: string;
	checkboxUnselected: string;
	dropdown: string;
	accountNavigation: string;
	submenu: string;
	autosExpression: string;
	client: string;
	createNew: string;
	menuDark: string;
	menuLight: string;
	editorRow: string;
	editorElement: string;
	editorRepeatable: string;
	error: string;
	warning: string;
	success: string;
	info: string;
	successIcon: string;
	errorIcon: string;
	infoIcon: string;
	warningIcon: string;
}

export interface IThemeBorderColors {
	primary1: string;
	primary2: string;
	primary3: string;
	primary4: string;
	primary5: string;
	secondary1: string;
	secondary2: string;
	secondary3: string;
	secondary4: string;
	secondary5: string;
	secondary6: string;
	white: string;
	altWhite: string;
	background: string;
	blue400: string;
	teal400: string;
	teal500: string;
	pink400: string;
	red400: string;
	red600: string;
	green600: string;
	purple400: string;
	orange400: string;
	grayAlpha: string;
	grayAlpha100: string;
	grayAlpha400: string;
	gray100: string;
	gray1: string;
	gray2: string;
	medgray1: string;
	medgray2: string;
	darkgray1: string;
	darkgray2: string;
	darkgray3: string;
	text: string;
	inverseText: string;
	black: string;
	checkboxUnselected: string;
	dropdown: string;
	accountNavigation: string;
	submenu: string;
	autosExpression: string;
	client: string;
	createNew: string;
	menuDark: string;
	menuLight: string;
	editorRow: string;
	editorElement: string;
	editorRepeatable: string;
	error: string;
	warning: string;
	success: string;
	info: string;
	successIcon: string;
	errorIcon: string;
	infoIcon: string;
	warningIcon: string;
}

export interface IThemeStyles {
	buttonBorderRadius: string | number;
}

export interface IThemeReportColors {
	box1: string;
	box2: string;
	box3: string;
	box4: string;
	box5: string;
	box6: string;
	box7: string;
	box8: string;
	text: string;
	unsubChart: string;
	bounceChart: string;
	lowChart: string;
	circleChart1: string;
	circleChart2: string;
	circleChart3: string;
	restChart1: string;
	restChart2: string;
	restChart3: string;
	restChart4: string;
	restChart5: string;
	restChart6: string;
	restChart7: string;
	restChart8: string;
	restChart9: string;
	restChart10: string;
	restChart11: string;
	restChart12: string;
}

export interface IStyledTheme {
	fontColors: IThemeFontColors;
	backgroundColors: IThemeBackgroundColors;
	borderColors: IThemeBorderColors;
	styles?: IThemeStyles;
	reportColors?: IThemeReportColors;
}

export interface IMooskinContext {
	locale?: Locale;
	setLocale?: (locale: ISupportedLanguage) => void;
	palette?: IStyledTheme;
}
